version: '3.1'

services: 
  nginx:
    image: nginx:latest
    container_name: nginx_container
    command: ""
    ports: 
    - 81:80
    volumes: 
      - ./web:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php7
  
  php7:
    image: php:7.3-fpm
    restart: always
    container_name: php73_container
    ports:  
      - 9010:9000
    volumes:
      - ./web:/usr/share/nginx/html
